```{r}
data_imb_n <- read.csv("../output/inputs/non-zero-mean/n.json.csv")
data_imb_2n <- read.csv("../output/inputs/non-zero-mean/2n.json.csv")
data_lin_100 <- read.csv("../output/inputs/different_initial/lin_100.json.csv")
data2L <- read.csv("../output/inputs/different_p/1e-2_L.json.csv")

data_lin_100 = data_lin_100[data_lin_100$i>0 &data_lin_100$p_t>0,]
data_imb_n = data_imb_n[data_imb_n$i>0 &data_imb_n$p_t>0,]
data_imb_2n = data_imb_2n[data_imb_2n$i>0 &data_imb_2n$p_t>0,]
data2L <- data2L[data2L$i>0 & data2L$p_t >0,]

```


## Perform robust linear regression



```{r}
p <- ggplot(data_imb_2n) +
  geom_line(aes(x=i, y=p_t, color="imb2n"))+
  geom_line(data=data_imb_sym,aes(x=i, y=p_t, color="imbsym"))+
  geom_line(data=data_lin_100, aes(x=i, y=p_t, color="lin_100"))+
  geom_line(data=data2L, aes(x=i, y=p_t, color="2L"))+
  stat_function(fun = function(x) {r=x^(-1.163321)*9855.04127203253; return(pmin(c(r),1))}, aes(color="imbsym"),linetype="dashed")+
  stat_function(fun = function(x) {r=x^(-1.151799)*145856.52768537975; return(pmin(c(r),1))}, aes(color="imb2n"),linetype="dashed")+
  stat_function(fun = function(x) {r=x^(-1.031223)*439259.3264274979; return(pmin(c(r),1))}, aes(color="lin_100"),linetype="dashed")+
  stat_function(fun = function(x) {r=x^(-1.158010)*2866554.715353357; return(pmin(c(r),1))}, aes(color="2L"),linetype="dashed")+
  scale_x_log10(limits=c(1, 1e8))+
  xlab("n")+
  ylab("survival rate")+
  labs(color=NULL)+
  scale_y_log10(labels=percent, breaks=c(0.000001,0.0001,0.01,1), limits=c(0.00001, 10))+
  scale_color_manual(values = c(
    "imb2n"="#E63946",
    "lin_100"="#F4A261",
    "2L"="#2A9D8F",
    "imbsym"="#8E44AD"
  ),
  labels = c(
    "imb2n"=expression(E(X[n])~"="~2*n+20), 
    "lin_100"=expression(y[0]~ "=" ~100), 
    "2L"=expression(p~"="~0.99), 
    "imbsym"=expression(E(X[n])~"="~0)
  )) +
  guides(color=guide_legend(reverse = FALSE))+
  theme_half_open()+
  theme(legend.position="inside",legend.position.inside=c(0.75,0.85))

print(p)
ggsave("explicit_bound_examples.pdf",width=7, height=5)
```